from enum import Enum

Weapon_type = Enum('Weapon_type', ['NONE',
                                   'ONE_HANDED_SWORD',
                                   'TWO_HANDED_SWORD',
                                   'ONE_HANDED_SPEAR',
                                   'TWO_HANDED_SPEAR',
                                   'ONE_HANDED_AXE',
                                   'TWO_HANDED_AXE',
                                   'KATANA',
                                   'HAMMER',
                                   'CARD',
                                   'MACE',
                                   'RAPIER',
                                   'DAGGER',
                                   'SHURIKEN',
                                   'SOUL',
                                   'REVOLVER',
                                   'GATLING_GUN',
                                   'RIFLE',
                                   'SHOTGUN',
                                   'GRENADE_LAUNCHER',
                                   'BAZOOKA',
                                   'BOOK',
                                   'KNUCKLE',
                                   'BOW',
                                   'ARBALEST',
                                   'INSTRUMENT',
                                   'WHIP',
                                   'KUNAI',
                                   'CLAW',
                                   'KATAR',
                                   'ONE_HANDED_ROD',
                                   'ONE_HANDED_WAND',
                                   'TWO_HANDED_STAFF'])